### ISSUE TITLE
Why is force unwrap used in UIView extensions?

### ISSUE THREAD

**Issue by TadeasKriz** [SwiftBond/Bond#119]
Hi, I noticed that in Bond extensions for UIView, there is rather strange construct:
```
    if let d: AnyObject = objc_getAssociatedObject(self, &textDynamicHandleUILabel) {
      return (d as? Dynamic<String>)!
    } else {
        ...
    }
```

and I was asking myself why it is not implemented this way:

```
    if let d = objc_getAssociatedObject(self, &textDynamicHandleUILabel) as? Dynamic<String> {
      return d
    } else {
        ...
    }
```

which would be definitely more safe than force unwrap. Is there some hidden reason behind this?

**Comment by srdanrasic** [comment]
A relic form Swift 1.0 I suppose. Does not really matter in this case because we are sure that if there is an object associated with that key, it will be our type. Unless someone messed with internal workings of the library, but in that case it's probably better to crash then to allow incorrect behaviour.

Will make sure this comes out nicer in next version, though!
