### ISSUE TITLE
No accessible initializers for Dispatcher

### ISSUE THREAD

**Issue by zipme** [SwiftBond/Bond#135]
When I try to create a dispatcher instance `let dispatcher = Dispatcher<MyComponentEvent>()`
I got this error:
`'Dispatcher<ProjectDetailsViewEvent>' cannot be constructed because it has no accessible initializers`

**Comment by srdanrasic** [comment]
Yeah, it's missing the public initializer. Why are you using Dispatcher anyway and not the Observable?

**Comment by zipme** [comment]
I only need a very simple event emitter, that's why I use Dispatcher.
I am trying out Observable now as you suggested, any idea which initializer I should use?

For example, I have an event type:

```
enum MyEventType {
 case EventA, EventB
}
```

To create an instance of Observable, I  do `let observable = Observable()`
And to send a event `observable.next(MyEventType.EventA)` which gives an error.

If I do `Observable(MyEventType.EventA)` then everything works fine. What bothers me is that in order to have an initial event for Observable during initialization, I need to add something like `case Empty` to `MyEventType`.

Did I do something wrong here?

**Comment by srdanrasic** [comment]
The observable you need obviously does not have an initial value, which is fine. There are two issues with `let observable = Observable()` approach. First is that there is no such initializer, second is that Swift cannot infer event type because it is not specified.

For now, add this somewhere to you code:

```swift
extension Observable {
  convenience init() {
    self.init(lifecycle: .Normal, producer: { sink in return nil })
  }
}
```

Then you'll be able to do:

```swift
let observable = Observable<MyEventType>()
observable.next(.EventA)
```

I'll improve this use case for Alpha 3 release so that there is no need for the extension.

**Comment by zipme** [comment]
👍👍👍

Cool! Thanks for the info!
