### ISSUE TITLE
Cannot invoke initializer for type 'ObservableArray<ElementType>' with an argument list of type '(NSArray)'

### ISSUE THREAD

**Issue by retsohuang** [SwiftBond/Bond#148]
Can't combine two type of ObservableArray to one

```swift
let channels = ObservableArray<Channel>
let photo = ObservableArray<NSURL>
ObservableArray([channels, photo])
```

**Comment by srdanrasic** [comment]
Yes, that will not work because Array is a generic type generalized over its element type. You cannot have elements of different types. Just like Swift Array cannot be initialized with elements of different types: `let array = [1, 2, "a", "b"]` does not compile.

You could solve this by having your arrays as arrays of AnyObjects, like 

```swift
let channels = ObservableArray<AnyObject>
let photo = ObservableArray<AnyObject>
ObservableArray([channels, photo])
```

And then downcast when using:

```swift
let firstChannel = channels[0] as! Channel
```

This is of course not ideal solution because you loose type information.

**Comment by retsohuang** [comment]
Thanks for replay, do you have any ideas that I can use multiple section with different view model bind to a table view like v 3.X does?

**Comment by srdanrasic** [comment]
Hmm, v3 also did not support that. There is no way to make it work at the moment... I'll add this as an enhancement for v4.1.

**Comment by retsohuang** [comment]
Thank you!!
