### ISSUE TITLE
Bond API stability?

### ISSUE THREAD

**Issue by joshavant** [SwiftBond/Bond#161]
What are the general thoughts from the maintainers about the API stability of Bond, moving forward from v4?

The v3 > v4 transition included some significant breaking API changes as well as some philosophical changes in functionality. For our project, we've had to allocate an entire week towards migration to v4.

Do you expect breaking API/functionality changes like this to happen often? Will there be plans for legacy support in future revisions? Hopefully Bond is a little more settled, now that Swift 2 is officially out? :)

In any case, v4 feels like a great improvement over v3! Thanks for all of your time building and maintaining this amazing tool!

**Comment by srdanrasic** [comment]
No, there are no breaking changes in sight and all future updates should be just extensions that introduce new capabilities without changing existing APIs.

It was not easy decision to change everything in v4 but, trust me, it was necessary in order to make the framework future proof.

Sorry for that week, hope it will pay off in a long run :)

**Comment by joshavant** [comment]
Thanks for the update, glad to hear all of this!

FWIW, as I'm migrating, I really like the syntax and direction of v4, as compared to v3. Awesome work!

**Comment by srdanrasic** [comment]
Thanks!
