### ISSUE TITLE
combineLatest([EventProducerType])

### ISSUE THREAD

**Issue by aputinski** [SwiftBond/Bond#169]
What is the best pattern to combine an unknown number of event producers?

**Comment by hzahnlei** [comment]
Hello.
This is my first post here and I want to support this question.
I have built a user registration screen.
The "register user" button gets enabled only if all required fields are filled out.
With Bond 3 I was just nesting several calls to `reduce()`.
Alternatively I created my own `reduce()` function that was built after Bond's `reduce()` but accepting more parameters.
With Bond 4 I have moved to `combineLatest()`.
Again I built my own version of `combineLatest()` that accepts the number of parameters I desire.
I did that by chaining `combineLatest()` with increasing arity, starting with four arguments, since Bond already provides `combineLatest()` with two and three arguments.
However, I am not sure this is the right approach.
Especially given that the absolutely harmless mapping function caused an "expression to complex to be solved in reasonable time" error.
Any help appreciated.
Thank you, great framework.

**Comment by srdanrasic** [comment]
Sorry for not responding earlier. Are all event producers you need to combine into one event producer of the same type? There was function `any` in v3 which I forgot to port, but should be simple. Alternatively, we can add additional overloads for combineLatest that accepts more producers.

**Comment by aputinski** [comment]
The event producers would all be of different type. I was looking for something similar to this:

https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift2/ReactiveCocoa/Swift/Signal.swift#L1362

I tried writing a something like:

```swift
[a,b,c].reduce(a) { $0.combineLatestWith($1) }
```

but I couldn't get that to compile.

**Comment by srdanrasic** [comment]
That RAC method accepts a sequence of signals where all signals are of the same type. Same thing could be easily added to Bond.

If your event producers are of different type, what type would be the events the combined producer generates? `Any`?

**Comment by aputinski** [comment]
What would your recommendation be? Is a sequence the wrong way to approach the problem? I noticed that RAC has overloads for `combineLatest` that go up to 10 arguments.

**Comment by hzahnlei** [comment]
My use case is similar to Adam's in that all event producers potentially have a different type.

I added my own `combineLatest()` functions in addition to Bond's:

```swift
public func combineLatest<A: EventProducerType, B: EventProducerType, C: EventProducerType, D: EventProducerType>( a: A, _ b: B, _ c: C, _ d: D ) -> EventProducer<(A.EventType, B.EventType, C.EventType, D.EventType)> {
    return combineLatest( a, b, c ).combineLatestWith( d ).map { ($0.0, $0.1, $0.2, $1) }
}

public func combineLatest<A: EventProducerType, B: EventProducerType, C: EventProducerType, D: EventProducerType, E: EventProducerType>( a: A, _ b: B, _ c: C, _ d: D, _ e: E ) -> EventProducer<(A.EventType, B.EventType, C.EventType, D.EventType, E.EventType)> {
    return combineLatest( a, b, c, d ).combineLatestWith( e ).map { ($0.0, $0.1, $0.2, $0.3, $1) }
}
.
.
.
public func combineLatest<A: EventProducerType, B: EventProducerType, C: EventProducerType, D: EventProducerType, E: EventProducerType, F: EventProducerType, G: EventProducerType, H: EventProducerType>( a: A, _ b: B, _ c: C, _ d: D, _ e: E, _ f: F, _ g: G, _ h: H ) -> EventProducer<(A.EventType, B.EventType, C.EventType, D.EventType, E.EventType, F.EventType, G.EventType, H.EventType)> {
    return combineLatest( a, b, c, d, e, f, g ).combineLatestWith( h ).map { ($0.0, $0.1, $0.2, $0.3, $0.4, $0.5, $0.6, $1) }
}
```

Of course, this approach is not universal.
You cannot have an arbitray number of event producers.
You have to add another `combineLatest()` functions should you need 9 parameters instead of the 8 I am offering.

Furthermore, the Swift compiler was complaining.
It issued an "Expression to complex to be solved in reasonable time" error when I was using my own method like this:

```swift
combineLatest( self.status, self.settings.userId, self.firstName, self.lastName, self.email, self.emailRepeated, self.password, self.repeatedPassword ).map {
    status, userId, firstName, lastName, email, emailRepeated, password, passwordRepeated in
       return
            status == 0
        &&  isValidUserId( userId )
        &&  firstName != "" && lastName != ""
        &&  isValidEmailAddress( email ) && emailRepeated == email
        &&  isValidPassword( password ) && passwordRepeated == password
} ->> self.registerAccountButtonEnabled
```

However, everything works fine, when I use it like this:

```swift
combineLatest( self.status, self.settings.userId, self.firstName, self.lastName, self.email, self.emailRepeated, self.password, self.repeatedPassword ).map {
    status, userId, firstName, lastName, email, emailRepeated, password, passwordRepeated in
        let nameOK = firstName != "" && lastName != ""
        let emailOK = isValidEmailAddress( email ) && emailRepeated == email
        let passwordOK = isValidPassword( password ) && passwordRepeated == password
        return
            status == 0
        &&  isValidUserId( userId )
        &&  nameOK
        &&  emailOK
        &&  passwordOK
} ->> self.registerAccountButtonEnabled
```

The strange thing is, that Swift 2.0 was complaining that the `return` expression was to complex.
This was no issue with Swift 1.2.
Actually, I would have been less surprised if my cascade of `combineLatest()` functions would have caused an error.

This is why I am not sure my approach is advisable.
Nevertheless, it seems to work fine.
Breaking up the return statement seems to do the trick.

**Comment by srdanrasic** [comment]
Added up to 10 overloads to combineLatest in v4.0.2.
