### ISSUE TITLE
Question about eventDynamic 

### ISSUE THREAD

**Issue by pasviegas** [SwiftBond/Bond#17]
In the code below the startSprint (and stopSprint) gets triggered as soon as I open the screen.

Am I doing something wrong?

````swift
    override func viewDidLoad() {
        super.viewDidLoad()
        
        startClick = startButton.eventDynamic().filter { $0 == UIControlEvents.TouchUpInside }  ->> {
            [unowned self] event in
            self.project!.startSprint()
        }
        
        stopClick = stopButton.eventDynamic().filter { $0 == UIControlEvents.TouchUpInside } ->> {
            [unowned self] event in
            self.project!.stopSprint()
        }
    }
````

Thanks.

**Comment by srdanrasic** [comment]
This is great catch, I wonder it didn't came up earlier.

Operator `->>` binds and fires with current value. There is a flaw in implementation of `filter` with regard to current value of filtered dynamic. This will be fixed in the next version, hopefully this weekend.

What you should do is use operator `->|` when observing events that should not fire at binding time.

In other words, operator `->>` binds objects and calls Listener closure with current value. Operator `->|` just binds objects (Listener will get called only on subsequent changes).

Hope it helps.

**Comment by pasviegas** [comment]
Cool, and thanks a lot for updating the readme :D

**Comment by srdanrasic** [comment]
Hi Pedro. Bond v3 is out. With it you can do your example like this:

```swift
class ViewController: UIViewController
{  
  lazy var startClick: Bond<UIControlEvents> = Bond() { [unowned self] event in
    self.project!.startSprint()
  }
  
  lazy var stopClick: Bond<UIControlEvents> = Bond() { [unowned self] event in
    self.project!.stopSprint()
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    startButton.dynEvent.filter(==, .TouchUpInside) ->> startClick
    stopButton.dynEvent.filter(==, .TouchUpInside) ->> startClick
  }
}
```
