### ISSUE TITLE
Common Protocol for all Dynamic<T> classes?

### ISSUE THREAD

**Issue by rvangraan** [SwiftBond/Bond#49]
Hi there,

is there a possibility that you can introduce an empty protocol that all the Dynamic<T> types implement, similar to this? 
```
protocol DynamicProtocol {}

public class Dynamic<T> : DynamicProtocol {
}
```

We would like to declare an array or set that can store the dynamic instances, but can't do that if they don't all have a common extension.

We have this kind of thing in our code base:

```
    private description: String = ""
    private var dynDescription = Dynamic(description)
    private var dynNetAmount = Dynamic(Money())
    private var dynVatAmount = Dynamic(Money())
   ...
```

and it would be really cool if we can declare a container like this that store any Dynamic<T> instance:

```
var dynamicValues : [ ValueType: DynamicProtocol ]
dynamicValues[.description] = dynDescription
dynamicValues[.vatAmount] = dynVatAmount
...
```
We cannot do this at the moment because of the generic Dynamic<T> type, but it will be possible all the Dynamic classes implement a single protocol without methods.

Thanks,

R

**Comment by srdanrasic** [comment]
Hi @rvangraan,

You should be able to do that yourself with extensions, like this:

```swift
protocol DynamicProtocol {}
extension Dynamic: DynamicProtocol {}
```

Then you can declare an array of Dynamics of any generic type:

```swift
var dynamicValues = [DynamicProtocol]()
    
dynamicValues.append(Dynamic<Int>(0))
dynamicValues.append(Dynamic<String>("hi"))
```

That being said, for whatever reason you might need this, I'm not sure it's good approach. First of all, type information will be lost, so you'll need to cast to right type before binding:

```swift
(dynamicValues[1] as! Dynamic<String>) ->> nameLabel
```

Additionally, if you replace a dynamic element in the array, the binding will be lost. For example, if you do:

```swift
dynamicValues[1] = Dynamic<String>("Tim")
```

Then updating that new dynamic would not propagate to name label because that new Dynamic is not bound to it.

I'd strongly recommend against doing all this.

Thanks
