### ISSUE TITLE
About Bond<T>.bondedDynamics

### ISSUE THREAD

**Issue by weiqingfei** [SwiftBond/Bond#76]
When I read the source of Bond, I found there is a property [bondedDynamics] in class Bond<T>.
I don't know why the property is needed, what will happen if just use the property [bondedWeakDynamics]?

**Comment by srdanrasic** [comment]
You should not use any of those properties. They should have been marked internal/private.

To answer your question, when you bind a Dynamic to a Bond, it's retained by [bondedDynamics]. The other one, [bondedWeakDynamics], is used in cases when we don't want strong reference, for example for feedback Bond in two-way binding: 
https://github.com/SwiftBond/Bond/blob/master/Bond/Bond%2BOperators.swift#L85-L88

Why are you using this properties anyway?

**Comment by weiqingfei** [comment]
Thanks for your reply.
Actually I don't use the properties directly. I just wonder why the Dynamic must be retained(strong reference) by Bond.
Normally we create a Dynamic retained by a viewModel, when we bind it to a Bond, then the Dynamic will be retained by 2 objects.
what will happen if we only let Bond to weak reference to Dynamics?

**Comment by srdanrasic** [comment]
Functions like map or filter return a Dynamic that's not referenced by anyone. For example, in order for this this to work:

```swift
viewModel.name.map { $0.uppercaseString } ->> nameLabel
```

Bond on `nameLabel`'s `dynText` must strongly reference result of mapping or it would get lost. This does not case any issues because (I assume) both your ViewModel and your Views (labels, etc...) are referenced by your ViewController, so when ViewController is deallocated, it will trigger deallocation of ViewModel, Views, Dynamics i.e. Bonds retained by Views, and finally of other Dynamics bound to those Dynamics, i.e. Bonds.

If you bind Dynamic to Bond weakly, it will work normally, but you have to make sure Dynamic stays alive.

**Comment by weiqingfei** [comment]
Thanks for your reply.
I think I know why. Very clever design.
I'm a newbie to swift, and fear using strong references, I tend to make a object retained by only one as possible.
Thanks again.

**Comment by srdanrasic** [comment]
You should not care how many references there are. It does not make application faster or better in any way. All that is important to understand is relationship graph, i.e. who owns whom. Also, beware of reference cycles when working with closures.

Swift book explains those concept pretty good: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AutomaticReferenceCounting.html

**Comment by weiqingfei** [comment]
Thank you for your kind reply.
I will study the document.
