### ISSUE TITLE
The listener always be fired by setting value.

### ISSUE THREAD

**Issue by weiqingfei** [SwiftBond/Bond#77]
I found the listener always be fired by setting value, even the value isn't changed.
For example in the Demo source
https://github.com/SwiftBond/Bond-Demo-App/blob/master/BondDemo/LoginViewModel.swift
```swift
  var loginButtonEnabled: Dynamic<Bool> {
    let usernameValid = username.map { countElements($0) > 2 }
    let passwordValid = password.map { countElements($0) > 2 }
    return reduce(usernameValid, passwordValid, loginInProgress) { $0 && $1 && $2 == false }
  }
```
when I input something into username textfield, if its length < 3, the usernameValid.value is still false, so the binding chain should be stopped to fire.

I attempt to compare new value and old value in class Dynamic, as you know generic can't be compared by "==".

So we can do nothing for this？

**Comment by srdanrasic** [comment]
That is expected. Setting the value (even same) triggers update. Framework does not check equality for multiple reason - it can impact performance, it can fail and it can be non-deterministic.

Is this causing any issues to you?

**Comment by weiqingfei** [comment]
Actually I haven't started a real app with this framework yet.
I just want to know how it works now.

Normally setting the same value will make the same result, if we can check the value's change, app will not to do same invalid work, especially in some case it will trigger a lot of update.

Sorry, maybe I was thinking too much.

**Comment by srdanrasic** [comment]
You asked valid question. It's good to think about it. There might be cases when this might be an issue, but this is not the one. Even if that reduce method was called thousand times a second, it would still have negligible impact on performance because expression in reduce method is very simple. On the other hand, if you were doing very complex or slow operation, like loading file from disk, or making network request, then you would have to think about performance and ways to limit number of requests.

**Comment by weiqingfei** [comment]
Thank you for your advice, I'll pay attention to that.
